### ISSUE TITLE
Inconsistent problem with cetune_report.db

### ISSUE THREAD

**Issue by tanghaodong25** [01org/CeTune#120]
Data from db is not consistent with data in dest_dir. 

For example:
In my test environment, there is two test result in dest_dir, I just get one test result from web UI. I must rm cetune_report.db in dest_dir and reload it to get consistent result.

**Comment by Shaoshian** [comment]
因为没有复现bug，暂时保留issue.

**Comment by tanghaodong25** [comment]
Can't reproduce, close this issue.
