### ISSUE TITLE
ceph-mgr daemon deployment

### ISSUE THREAD

**Issue by tanghaodong25** [01org/CeTune#258]
Need install 'ceph-mgr' daemon when deploy ceph 12.1.0+, or ceph will remain 'health_err' status...

Referring to the document: http://docs.ceph.com/docs/master/mgr/administrator/

**Comment by xuechendi** [comment]
@tanghaodong25 ， are you using latest codes, I remembered we added ceph-mgr support, can you check?

**Comment by tanghaodong25** [comment]
@xuechendi no, I'm not using the latest code. I'll check it with the new code.

**Comment by tanghaodong25** [comment]
I checked the master version. It supports "ceph-mgr". Close this issue.
