### ISSUE TITLE
what does CN_NUMBER mean?

### ISSUE THREAD

**Issue by hnuzhoulin** [01org/CeTune#295]
sorry to trouble you.
I know SN_NUMBER means the number of OSD servers.(maybe it is wrong)
But I get nothing about CN_NUMBER from code.

`tmp_data["CN_Number"] = len(data["client"]["cpu"])`

but the output is :

`In [13]: data['client']['cpu'].keys()
Out[13]: [u'detail', u'summary']`

**Comment by xuechendi** [comment]
CN is defined to be Client Node, and for CPU, we provides two kinds of data here, summary is used to show the average cpu ratio of each node, and detail is used to show cpu ratio of each core.

Anyway, you’ll get clearer idea when you check the CeTune webui results page.

Best regards,
Chendi

在 2018年3月13日，下午5:11，hnuzhoulin <notifications@github.com<mailto:notifications@github.com>> 写道：


sorry to trouble you.
I know SN_NUMBER means the number of OSD servers.(maybe it is wrong)
But I get nothing about CN_NUMBER from code.

tmp_data["CN_Number"] = len(data["client"]["cpu"])

but the output is :

In [13]: data['client']['cpu'].keys() Out[13]: [u'detail', u'summary']

―

**Comment by hnuzhoulin** [comment]
thanks.
so CN_NUMBER is alwayse 2.
