### ISSUE TITLE
how can I use cosbench to test?

### ISSUE THREAD

**Issue by guanglost** [01org/CeTune#36]
After reading CeTune Document.pdf,I confuse about the cosbench config.
Do I need to download the cosbench by myself? Or the cetune will download the cosbench itself?
would you give me an example for me to how to use cosbench to test

**Comment by guanglost** [comment]
when i now cetune is always return like
```
[2015-11-25T15:41:35.323376][LOG]: start to run performance test
[2015-11-25T15:41:35.324343][LOG]: Calculate Difference between Current Ceph Cluster Configuration with tuning
[2015-11-25T15:41:38.304664][LOG]: Tuning[analyzer] is not same with current configuration
[2015-11-25T15:41:38.784241][LOG]: Tuning has applied to ceph cluster, ceph is Healthy now
```
no more output
after this, there is no errer return,and I don't know what's the wrong for this

**Comment by xuechendi** [comment]
More log is under conf/cetune_process.log

And you should also put “python webui.py” at frontback, there will be some logs too

Did you specify your testcase under “benchmark configuration” part yet? I am thinking this may cause nothing happen after checking ceph health under cetune

And for the cosbench test, yes, cetune will help to download cosbench and kickoff cosbench daemons

**Comment by guanglost** [comment]
thank for answering!
more infomation:
In cases.conf
```
cosbench           0                  50           write           128KB                      64              30              60        cosbench
```
in all.conf under 
```
cosbench_version=v0.4.2.c2
cosbench_folder=/opt/cosbench
cosbench_config_dir=/opt/cosbench_config
cosbench_cluster_ip=10.1.0.12
cosbench_admin_ip=10.1.0.12
cosbench_network=10.1.0.0/24
cosbench_controller=controller3
cosbench_driver=controller3

rgw_num_per_server=1
cosbench_auth_username=cosbench
rgw_server=10.1.0.12
cosbench_auth_password=cosbench
cosbench_controller_proxy=""
```
python webui.py return the error:
```
Traceback (most recent call last):
  File "tuner.py", line 424, in <module>
    tuner.run()
  File "tuner.py", line 67, in run
    run_cases.main(['--tuning', section])
  File "/root/CeTune/benchmarking/run_cases.py", line 81, in main
    benchmark.go(testcase["parameter"], tuning_section)
  File "/root/CeTune/benchmarking/mod/benchmark.py", line 27, in go
    if not self.generate_benchmark_cases(self.benchmark):
  File "/root/CeTune/benchmarking/mod/bobject/cosbench.py", line 453, in generate_benchmark_cases
    benchmark["section_name"] = "%s-cosbench-%s-%s-%scon-%sobj-%s-%s-cosbench" % (benchmark["worker"], benchmark["iopattern"]["type"], benchmark["size"]["complete"], benchmark["container"]["max"], benchmark["objecter"]["max"], benchmark["rampup"], benchmark["runtime"])
KeyError: 'max'
```
cetune_process.log is no error .
In another thing,
now the radosgw is fine for the cluster. Do I need to config something about cosbench or cetune to connect to the radosgw?

**Comment by guanglost** [comment]
sorry  I have not  set the rang of the object and container
```
container_size: rbd-example: 10g cosbench-example: r(1,100)
object_size/QD: rbd-example: 64 cosbench-example: r(1,100)
```
I have resolved the problem

**Comment by guanglost** [comment]
How can I configure about cosbench write?
when the workers is set to 0
cosbench have two task:
```
op1: init -write
op1: prepare -write 
```
it will create mang data up to container_size * object_size ,not only create the container.which will take a long time.
in this situation,the running time is not useful.is this a bug?
how to use cetune in a good way?
