### ISSUE TITLE
ceph cluster status during the tests

### ISSUE THREAD

**Issue by zhouyuan** [01org/CeTune#45]
It's better to collect the ceph cluster status during the tests also.

**Comment by xuechendi** [comment]
Done, PR https://github.com/01org/CeTune/pull/46, will collect ceph status like below:
  1 2015_12_23 16:11:28 HEALTH_OK
  2 2015_12_23 16:11:30 HEALTH_OK
  3 2015_12_23 16:11:31 HEALTH_OK
  4 2015_12_23 16:11:33 HEALTH_OK
  5 2015_12_23 16:11:34 HEALTH_OK
  6 2015_12_23 16:11:36 HEALTH_OK
  7 2015_12_23 16:11:38 HEALTH_OK
  8 2015_12_23 16:11:39 HEALTH_OK
  9 2015_12_23 16:11:41 HEALTH_OK
 10 2015_12_23 16:11:43 HEALTH_OK
 11 2015_12_23 16:11:44 HEALTH_OK
 12 2015_12_23 16:11:46 HEALTH_OK
