### ISSUE TITLE
using fdisk to check whether the rbd image is attached is not reliable

### ISSUE THREAD

**Issue by hnuzhoulin** [01org/CeTune#55]
fdisk output is :

![image](https://cloud.githubusercontent.com/assets/6347012/13806964/b11aa8ce-eb99-11e5-8cea-d9e7c0ff94db.png)

but the output of lsblk is:

root@vclient01:~# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
vda    253:0    0    20G  0 disk
├─vda1 253:1    0   3.8G  0 part [SWAP]
└─vda2 253:2    0  16.2G  0 part /

this error occur every time when I create two or more benchmark cases.
when it deattch,the fdisk info is still exist until reboot vclient.

**Comment by xuechendi** [comment]
Thanks for your feedback.

Which acts quite different from our inside lab cetune cluster.

Actually we never reboot vm, and fdisk works just fine.

We are using Ubuntu 12.04 as the vm os, can I know what VM os is under you cluster?

Best regards,
Chendi

**Comment by hnuzhoulin** [comment]
ok，maybe my vm has some error.I will check it.
thanks for so fast reply. :+1:

**Comment by hnuzhoulin** [comment]
yes,this is the problem of my vm.
after I reboot it,everything works fine.
sorry.

**Comment by xuechendi** [comment]
Got it, Thanks for informing ☺

Best regards,
Chendi
