### ISSUE TITLE
Always show "Benchmark is running..."

### ISSUE THREAD

**Issue by t19903** [01org/CeTune#98]
I have just installed CeTune and start up the web ui. However, it shows "Benchmark is running..." on the browser, and seems not working at all.

**Comment by xuechendi** [comment]
@t19903 , in that case, that is because there occurs some error in your cetune deployment, 'benchmark is running' is a fake page which means cetune is not fully running.
Can you kindly check conf/cetune_process.log and the printout after you ran python webui.py to see what causes this issue.

**Comment by t19903** [comment]
Ah, thx. After adding head, list_server, list_mon to all.conf it works now. I thought I can set the config through web UI, but seems I have to give at least three value to make it work and then to add more configuration through web UI.

**Comment by xuechendi** [comment]
@t19903 , oh, thanks for the information, that sounds quite not friendly, we will fix this in the near future. Thanks again.

**Comment by t19903** [comment]
Thank you for your kind reply :).
